spring.application.name=blackjack
# blackjack.simulation.count=100000
# blackjack.simulation.initial-money=1000000
# blackjack.simulation.bet-amount=100
# blackjack.simulation.deck-count=6
# blackjack.simulation.shuffle-threshold=0.8
